name: opgg
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.16.0-80.0.dev <3.0.0'


dependencies:
  material: ^1.0.0+2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.20.1

flutter:
  assets:
    - assets/logo.png

  uses-material-design: true